name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installation Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Installation des d√©pendances
        run: npm install --legacy-peer-deps

      - name: Configuration Gradle
        run: cd android && chmod +x gradlew

      - name: Compilation de l'APK (Debug)
        run: cd android && ./gradlew assembleDebug --no-daemon

      - name: Upload de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: MalinWallet-Android-App
          path: android/app/build/outputs/apk/debug/app-debug.apk

